### ISSUE TITLE
Privacy concerns

### ISSUE THREAD

**Issue by linksky56** [dessant/clear-browsing-data#16]
Not sure if this is the correct place to post this? but anyway?

Really like this extension, exactly what i was looking for. 
My concern is about permissions, "Access your data for all websites". Why?
I noticed the other "clear-browser" add-ons don't require this permission. Why do you need to "Access your data for all websites" to clear browsing history, cookies, and related data, while none of the other add-ons similar to yours require this permission.

I noticed you don't have a stated 'Privacy Policy". What is your privacy policy?

Do you really need to "Access your data for all websites"?

Please ease my concerns, so i can use and donate to this wonderful add-on, thanks

**Comment by dessant** [comment]
The extension does not collect data, the permission was part of a feature that did not end up being included for now: managing cookies per host.

I plan to include that feature at some point, so the permission will be left there because reintroducing it later on would cause disruption and loss of users, at least that has been my experience every time my extensions have requested new permissions that were required for new features.

**Comment by linksky56** [comment]
Thanks for the quick reply and thanks erasing any privacy concerns i had. 
I now can start using this wonderful add-on.

Regarding, "so the permission will be left there because reintroducing it later on would cause disruption and loss of users, at least that has been my experience every time my extensions have requested new permissions that were required for new features". You're right, I'm one of those paranoid people, who would be skeptical and maybe even quit using the extension. lol

FWIW, I think it would be great if you added a managing cookies per host feature at some point.

Thanks again for the explanation.

**Comment by dessant** [comment]
This extension will be included in the Recommended Extensions program, so unused permissions have been removed.

https://github.com/dessant/clear-browsing-data/commit/1ddf2bdc7e81906dfebea3b5ae244aeb730d4e31
