### ISSUE TITLE
is this still in development?

### ISSUE THREAD

**Issue by russeg** [dessant/clear-browsing-data#49]
is it? there are some bugs that have not been addressed and some features (like scheduled clearing) that have not been implemented.

anyway, i have moved on to "Cookie AutoDelete".

**Comment by dessant** [comment]
The project is still maintained, and I'm not aware of any bugs that are caused by the extension, the issues with leftover browsing data are caused by documented browser bugs. As for feature requests, you can sponsor the development of a specific feature, if you'd like the project to progress at the pace you expect.
