### ISSUE TITLE
Single Tab Clear

### ISSUE THREAD

**Issue by aemonge** [dessant/clear-browsing-data#7]
Is it posible to only clean the current/active site ?

**Comment by dessant** [comment]
Hi, sorry for the late reply! It is not currently possible to clear browsing data for a single tab.

The browsing data API allows clearing only cookies and local storage for a specific domain, and only in Firefox:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browsingData/RemovalOptions

Cookies could be cleared on Chrome with the cookies API:

The history could also be cleared through a different APIs for a specific URL:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history/deleteUrl

This is rather incomplete, and could be dangerous to have it implemented in such a spotty way, because it would break expectations of what is deleted, and what is kept.

For now it seems this feature will have to be shelved, but I'll be happy to revisit this once browsers will have proper support for clearing browsing data for a tab.
